base:
  project: mlops-insurance
  random_state: 42
  target_col: chargers

data_source:
  s3_source: source_code/insurance_course5i.csv  # local_source

load_data:
  raw_dataset_csv: data/raw/insurance_course5i.csv # load data from local

split_data:
  train_path: data/processed/train_insurance_course5i.csv
  test_path: data/processed/test_insurance_course5i.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      li_ratio: 0.4

model_dir: models

reprts: 
  params: reports/params.json
  scores: reports/scores.json
  
webapp_model_dir: prediction_service/model/model.joblib

